# action.yml
name: 'Run jenkins jobs'
description: 'Build jenkins jobs using the jenkins api'
inputs:
  jenkins-url:
    description: 'full Jenkins site url'
    required: true
  jenkins-token:
    description: 'Jenkins api token'
    required: true
  jenkins-user:
    description: "Jenkins username"
    required: true
  jenkins-job:
    description: 'Jenkins job name'
    required: true
  jenkins-job-params:
    description: "Jenkins job params. JSON string. i.e '{'STRING_PARAM': 'value1', 'BOOLEAN_PARAM': false}' "
    required: false
    default: '{}'
  jenkins-wait-job: 
    description: "Wait for the job build status"
    required: false
    default: 'wait'
outputs:
  job_build_number:
    description: 'buildnumber of the triggered job'
  job_status:
    description: 'Jenkins job build status'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.jenkins-url}}
    - ${{ inputs.jenkins-token}}
    - ${{ inputs.jenkins-user}}
    - ${{ inputs.jenkins-job }}
    - ${{ inputs.jenkins-job-params}}
    - ${{ inputs.jenkins-wait-job }}
branding:
  icon: 'arrow-up-right'
  color: 'yellow'
