# action.yml
name: 'Run jenkins jobs'
description: 'Build jenkins jobs using the jenkins api'
inputs:
  jenkins-url:
    description: 'full Jenkins site url'
    required: true
  jenkins-token:
    description: 'Jenkins api token'
    required: true
  jenkins-user:
    description: "Jenkins username"
    required: true
  jenkins-job:
    description: 'Jenkins job name'
    required: true
  jenkins-wait-job:
    description: 'Wait for the job build status'
    required: false
    default: '--no-wait-job'
  jenkins-job-params:
    description: "Jenkins job params. JSON string. i.e '{'STRING_PARAM': 'value1', 'BOOLEAN_PARAM': false}' "
    required: false
outputs:
  job_status:
    description: 'Jenkins job build status'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - -host ${{ inputs.jenkins-url}}
    - -tk ${{ inputs.jenkins-token}}
    - -u ${{ inputs.jenkins-user}}
    - -jb ${{ inputs.jenkins-job }}
    - -p ${{ inputs.jenkins-job-params}}
    - ${{ inputs.jenkins-wait-job}}
branding:
  icon: 'arrow-up-right'
  color: 'yellow'
