name: Run Unit Test

on:
  pull_request:
    branches: [ master ]

jobs:
  Running-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run python test
        uses: fylein/python-pytest-github-action@v1
        with:
          args: pip3 install -r requirements/test.txt && pip3 install -r requirements/base.txt && pytest test